# These are supported funding model platforms

github: [moises, lumina-alerts]
patreon: ["https://patreon.com/user?u=119821421&utm_medium=unknown&utm_source=join_link&utm_campaign=creatorshare_creator&utm_content=copyLink"
custom: ["https://paypal.me/JMoises89"]
